// Command conformance generates fixtures.json, the shared test vectors that
// the Go and TypeScript implementations of jwkit must agree on, and doubles as
// a tiny test issuer (see serve.go).
//
//	go run .            regenerate fixtures.json
//	go run . -check     fail if fixtures.json is not what the generator produces
//	go run . -new-keys  regenerate with fresh key pairs
//	go run . -serve :8089   serve the fixture JWKS and mint tokens
//	go run . -mutations 5000 -seed 1   write random mutations (see mutate.go)
//
// It uses only the Go standard library: tokens are built by hand and signed
// with crypto/rsa and crypto/ecdsa, so neither JOSE library under test had a
// hand in producing its own test vectors.
//
// Output is deterministic. Keys are reused from the existing fixtures.json,
// RSASSA-PKCS1-v1_5 is deterministic by definition, and ECDSA signatures use
// RFC 6979 nonces, so regenerating changes nothing unless a case changed.
// That is what makes the -check mode, which CI runs, possible.
package main

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/asn1"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"math/big"
	"os"
	"strings"
)

// The configuration every case is verified under. The clock is fixed so the
// fixtures never go stale.
const (
	issuer        = "https://issuer.jwkit.example"
	audience      = "https://api.jwkit.example"
	now           = 1_750_000_000 // 2025-06-15T15:06:40Z
	clockSkewSec  = 60
	maxTokenBytes = 8192
)

// Fixtures is the schema of fixtures.json.
type Fixtures struct {
	Description string `json:"description"`
	Config      Config `json:"config"`
	// Keys holds the private keys the tokens were signed with, so that the
	// file can be regenerated and so that a reader can mint further tokens.
	// They are test material and protect nothing.
	Keys []map[string]string `json:"test_private_keys"`
	// JWKS is the document the issuer publishes; runners serve it over HTTP.
	JWKS  map[string]any `json:"jwks"`
	Cases []Case         `json:"cases"`
}

// Config is what a runner must configure its verifier with.
type Config struct {
	Issuer        string `json:"issuer"`
	Audience      string `json:"audience"`
	Now           int64  `json:"now"`
	ClockSkewSec  int    `json:"clock_skew_sec"`
	MaxTokenBytes int    `json:"max_token_bytes"`
}

// Case is one token and the result both implementations must produce for it:
// "ok" or the name of a typed error.
type Case struct {
	Name   string `json:"name"`
	About  string `json:"about"`
	Token  string `json:"token"`
	Expect string `json:"expect"`
}

func main() {
	path := flag.String("fixtures", "fixtures.json", "path of the fixtures file")
	check := flag.Bool("check", false, "verify the fixtures file is up to date instead of writing it")
	newKeys := flag.Bool("new-keys", false, "generate fresh key pairs instead of reusing the ones in the fixtures file")
	serveAddr := flag.String("serve", "", "serve the fixture JWKS and mint tokens on this address instead of generating")
	mutations := flag.Int("mutations", 0, "write this many random mutations for differential testing instead of generating (see mutate.go)")
	seed := flag.Uint64("seed", 1, "with -mutations: the random seed")
	out := flag.String("out", "results/mutations.json", "with -mutations: where to write them")
	flag.Parse()

	if err := run(*path, *check, *newKeys, *serveAddr, *mutations, *seed, *out); err != nil {
		fmt.Fprintln(os.Stderr, "conformance:", err)
		os.Exit(1)
	}
}

func run(path string, check, newKeys bool, serveAddr string, mutations int, seed uint64, mutationsPath string) error {
	existing, readErr := os.ReadFile(path)

	var keys *keyring
	if newKeys || readErr != nil {
		if check || serveAddr != "" || mutations > 0 {
			return fmt.Errorf("%s is needed for this mode: %v", path, readErr)
		}
		keys = generateKeys()
	} else {
		var err error
		if keys, err = loadKeys(existing); err != nil {
			return fmt.Errorf("reading keys from %s: %w", path, err)
		}
	}

	if serveAddr != "" {
		return serve(serveAddr, keys)
	}
	if mutations > 0 {
		return writeMutations(mutationsPath, keys, mutations, seed)
	}

	out, err := render(keys)
	if err != nil {
		return err
	}
	if check {
		if !bytes.Equal(out, existing) {
			return fmt.Errorf("%s is out of date; run `make fixtures` and commit the result", path)
		}
		fmt.Printf("%s is up to date\n", path)
		return nil
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}

func render(keys *keyring) ([]byte, error) {
	cases := buildCases(keys)
	seen := map[string]bool{}
	for _, c := range cases {
		if seen[c.Name] {
			return nil, fmt.Errorf("duplicate case name %q", c.Name)
		}
		seen[c.Name] = true
	}
	fx := Fixtures{
		Description: "Conformance vectors for jwkit. Generated by conformance/gen_fixtures.go; do not edit by hand. " +
			"Every implementation must produce `expect` for each token when configured with `config` and the keys in `jwks`.",
		Config: Config{Issuer: issuer, Audience: audience, Now: now, ClockSkewSec: clockSkewSec, MaxTokenBytes: maxTokenBytes},
		Keys:   keys.privateJWKs(),
		JWKS:   keys.jwks(),
		Cases:  cases,
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(fx); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// ---------------------------------------------------------------------------
// Keys
// ---------------------------------------------------------------------------

// key is a signing key pair: RSA or EC, never both.
type key struct {
	kid string
	rsa *rsa.PrivateKey
	ec  *ecdsa.PrivateKey
}

func (k *key) alg() string {
	if k.rsa != nil {
		return "RS256"
	}
	return "ES256"
}

// keyring is every key the fixtures use.
type keyring struct {
	rsaCurrent  *key // published; signs the valid RS256 tokens
	ecCurrent   *key // published; signs the valid ES256 tokens
	rsaAttacker *key // never published
	rsaWeak     *key // published, but only 1024 bits: must not be loaded
	ecP384      *key // published, but the wrong curve for ES256: must not be loaded
	rsaEnc      *key // published with use=enc: must not be loaded
	rsaPS256    *key // published with alg=PS256: must not be loaded
}

func (r *keyring) all() []*key {
	return []*key{r.rsaCurrent, r.ecCurrent, r.rsaAttacker, r.rsaWeak, r.ecP384, r.rsaEnc, r.rsaPS256}
}

func generateKeys() *keyring {
	newRSA := func(kid string, bits int) *key {
		k, err := rsa.GenerateKey(rand.Reader, bits)
		must(err)
		return &key{kid: kid, rsa: k}
	}
	newEC := func(kid string, curve elliptic.Curve) *key {
		k, err := ecdsa.GenerateKey(curve, rand.Reader)
		must(err)
		return &key{kid: kid, ec: k}
	}
	return &keyring{
		rsaCurrent:  newRSA("rsa-current", 2048),
		ecCurrent:   newEC("ec-current", elliptic.P256()),
		rsaAttacker: newRSA("rsa-attacker", 2048),
		rsaWeak:     newRSA("rsa-weak-1024", 1024),
		ecP384:      newEC("ec-p384", elliptic.P384()),
		rsaEnc:      newRSA("rsa-enc", 2048),
		rsaPS256:    newRSA("rsa-ps256", 2048),
	}
}

func b64(b []byte) string { return base64.RawURLEncoding.EncodeToString(b) }

func unb64(s string) *big.Int {
	b, err := base64.RawURLEncoding.DecodeString(s)
	must(err)
	return new(big.Int).SetBytes(b)
}

func (k *key) publicJWK() map[string]any {
	if k.rsa != nil {
		return map[string]any{
			"kty": "RSA", "kid": k.kid,
			"n": b64(k.rsa.N.Bytes()),
			"e": b64(big.NewInt(int64(k.rsa.E)).Bytes()),
		}
	}
	// Bytes is the uncompressed SEC 1 point: 0x04 || X || Y.
	point, err := k.ec.PublicKey.Bytes()
	must(err)
	size := (len(point) - 1) / 2
	return map[string]any{
		"kty": "EC", "kid": k.kid, "crv": k.ec.Curve.Params().Name,
		"x": b64(point[1 : 1+size]),
		"y": b64(point[1+size:]),
	}
}

func (k *key) privateJWK() map[string]string {
	out := map[string]string{}
	for name, v := range k.publicJWK() {
		out[name] = v.(string)
	}
	if k.rsa != nil {
		out["d"] = b64(k.rsa.D.Bytes())
		out["p"] = b64(k.rsa.Primes[0].Bytes())
		out["q"] = b64(k.rsa.Primes[1].Bytes())
		out["dp"] = b64(k.rsa.Precomputed.Dp.Bytes())
		out["dq"] = b64(k.rsa.Precomputed.Dq.Bytes())
		out["qi"] = b64(k.rsa.Precomputed.Qinv.Bytes())
		return out
	}
	d, err := k.ec.Bytes()
	must(err)
	out["d"] = b64(d)
	return out
}

func (r *keyring) privateJWKs() []map[string]string {
	var out []map[string]string
	for _, k := range r.all() {
		out = append(out, k.privateJWK())
	}
	return out
}

// jwks is what the issuer publishes. Besides the two keys that sign valid
// tokens it contains keys an implementation must refuse to load, so that the
// fixtures also pin down key-set filtering.
func (r *keyring) jwks() map[string]any {
	with := func(k *key, extra map[string]any) map[string]any {
		j := k.publicJWK()
		for name, v := range extra {
			j[name] = v
		}
		return j
	}
	return map[string]any{"keys": []any{
		with(r.rsaCurrent, map[string]any{"use": "sig", "alg": "RS256"}),
		with(r.ecCurrent, map[string]any{"use": "sig", "alg": "ES256"}),
		with(r.rsaWeak, map[string]any{"use": "sig", "alg": "RS256"}),
		with(r.ecP384, map[string]any{"use": "sig"}),
		with(r.rsaEnc, map[string]any{"use": "enc"}),
		with(r.rsaPS256, map[string]any{"use": "sig", "alg": "PS256"}),
	}}
}

func loadKeys(fixtures []byte) (*keyring, error) {
	var fx Fixtures
	if err := json.Unmarshal(fixtures, &fx); err != nil {
		return nil, err
	}
	byKid := map[string]*key{}
	for _, j := range fx.Keys {
		k := &key{kid: j["kid"]}
		switch j["kty"] {
		case "RSA":
			k.rsa = &rsa.PrivateKey{
				PublicKey: rsa.PublicKey{N: unb64(j["n"]), E: int(unb64(j["e"]).Int64())},
				D:         unb64(j["d"]),
				Primes:    []*big.Int{unb64(j["p"]), unb64(j["q"])},
			}
			k.rsa.Precompute()
			if err := k.rsa.Validate(); err != nil {
				return nil, fmt.Errorf("key %q: %w", k.kid, err)
			}
		case "EC":
			curve := elliptic.P256()
			if j["crv"] == "P-384" {
				curve = elliptic.P384()
			}
			// The public point is recomputed from the private scalar.
			ec, err := ecdsa.ParseRawPrivateKey(curve, decode(j["d"]))
			if err != nil {
				return nil, fmt.Errorf("key %q: %w", k.kid, err)
			}
			k.ec = ec
		default:
			return nil, fmt.Errorf("key %q: unknown kty %q", k.kid, j["kty"])
		}
		byKid[k.kid] = k
	}
	r := &keyring{
		rsaCurrent: byKid["rsa-current"], ecCurrent: byKid["ec-current"], rsaAttacker: byKid["rsa-attacker"],
		rsaWeak: byKid["rsa-weak-1024"], ecP384: byKid["ec-p384"], rsaEnc: byKid["rsa-enc"], rsaPS256: byKid["rsa-ps256"],
	}
	for _, k := range r.all() {
		if k == nil {
			return nil, errors.New("a key is missing; regenerate with -new-keys")
		}
	}
	return r, nil
}

// ---------------------------------------------------------------------------
// Token construction
// ---------------------------------------------------------------------------

// sign returns the JWS signature of signingInput in the key's own algorithm.
func (k *key) sign(signingInput string) []byte {
	digest := sha256.Sum256([]byte(signingInput))
	if k.rsa != nil {
		sig, err := rsa.SignPKCS1v15(nil, k.rsa, crypto.SHA256, digest[:])
		must(err)
		return sig
	}
	r, s := k.ecdsaRS(digest[:])
	size := (k.ec.Curve.Params().BitSize + 7) / 8
	sig := make([]byte, 2*size)
	r.FillBytes(sig[:size])
	s.FillBytes(sig[size:])
	return sig
}

// signDER returns the ECDSA signature in ASN.1 DER, the encoding JWS does not use.
func (k *key) signDER(signingInput string) []byte {
	digest := sha256.Sum256([]byte(signingInput))
	// A nil random source selects deterministic RFC 6979 nonces.
	der, err := k.ec.Sign(nil, digest[:], crypto.SHA256)
	must(err)
	return der
}

func (k *key) ecdsaRS(digest []byte) (r, s *big.Int) {
	der, err := k.ec.Sign(nil, digest, crypto.SHA256)
	must(err)
	var sig struct{ R, S *big.Int }
	_, err = asn1.Unmarshal(der, &sig)
	must(err)
	return sig.R, sig.S
}

type obj = map[string]any

// toJSON encodes with sorted keys, which keeps the output deterministic.
func toJSON(v any) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	must(enc.Encode(v))
	return strings.TrimSuffix(buf.String(), "\n")
}

// signed assembles and signs a token from literal header and payload text.
func (k *key) signed(header, payload string) string {
	input := b64([]byte(header)) + "." + b64([]byte(payload))
	return input + "." + b64(k.sign(input))
}

func (k *key) header(extra ...obj) obj {
	h := obj{"alg": k.alg(), "kid": k.kid, "typ": "JWT"}
	for _, e := range extra {
		for name, v := range e {
			if v == nil {
				delete(h, name)
			} else {
				h[name] = v
			}
		}
	}
	return h
}

// claims returns a payload that is valid at `now`, with overrides applied.
// A nil override removes the claim.
func claims(overrides ...obj) obj {
	c := obj{"iss": issuer, "aud": audience, "sub": "user-123", "iat": now - 10, "exp": now + 3600}
	for _, o := range overrides {
		for name, v := range o {
			if v == nil {
				delete(c, name)
			} else {
				c[name] = v
			}
		}
	}
	return c
}

// token signs claims (with overrides) under the key's default header.
func (k *key) token(overrides ...obj) string {
	return k.signed(toJSON(k.header()), toJSON(claims(overrides...)))
}

// tokenWithHeader signs default claims under a modified header.
func (k *key) tokenWithHeader(extra obj) string {
	return k.signed(toJSON(k.header(extra)), toJSON(claims()))
}

// as returns the same key pair under a different kid.
func (k *key) as(kid string) *key {
	c := *k
	c.kid = kid
	return &c
}

func split(token string) (h, p, s string) {
	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		panic("split: not a three-segment token")
	}
	return parts[0], parts[1], parts[2]
}

func decode(segment string) []byte {
	b, err := base64.RawURLEncoding.DecodeString(segment)
	must(err)
	return b
}

// paddedTo returns a validly signed token of exactly n bytes, by sizing a
// filler claim. Lengths that the base64 arithmetic cannot reach with one
// header are reached with another.
func (k *key) paddedTo(n int) string {
	sigLen := len(b64(k.sign("x")))
	for _, extra := range []obj{{}, {"typ": nil}, {"typ": "at+jwt"}, {"typ": "JOSE"}} {
		header := toJSON(k.header(extra))
		for pad := 0; pad <= n; pad++ {
			payload := toJSON(claims(obj{"pad": strings.Repeat("x", pad)}))
			size := base64.RawURLEncoding.EncodedLen(len(header)) + 1 + base64.RawURLEncoding.EncodedLen(len(payload)) + 1 + sigLen
			if size == n {
				return k.signed(header, payload)
			}
			if size > n {
				break
			}
		}
	}
	panic(fmt.Sprintf("cannot build a token of exactly %d bytes", n))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

// ---------------------------------------------------------------------------
// The cases
// ---------------------------------------------------------------------------

func buildCases(keys *keyring) []Case {
	rs, es, attacker := keys.rsaCurrent, keys.ecCurrent, keys.rsaAttacker

	valid := rs.token()
	vh, vp, vs := split(valid)
	validES := es.token()
	eh, ep, esig := split(validES)

	rsHeader := toJSON(obj{"alg": "RS256", "kid": rs.kid})
	claimsJSON := toJSON(claims())
	adminPayload := b64([]byte(strings.Replace(claimsJSON, "user-123", "admin", 1)))

	// The same bytes with one bit of the decoded value flipped.
	flip := func(segment string) string {
		raw := decode(segment)
		raw[len(raw)/2] ^= 0x01
		return b64(raw)
	}
	// Only the unused trailing bits of the last character changed: a lenient
	// base64 decoder maps this to the same bytes as the original.
	nonCanonical := func(segment string) string {
		const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
		last := strings.IndexByte(alphabet, segment[len(segment)-1])
		out := segment[:len(segment)-1] + string(alphabet[last|1])
		if out == segment || !bytes.Equal(decode(out), decode(segment)) {
			panic("nonCanonical: could not build the encoding")
		}
		return out
	}
	unsigned := func(header obj) string {
		return b64([]byte(toJSON(header))) + "." + b64([]byte(claimsJSON)) + "."
	}
	// HS256 with the issuer's RSA public key as the HMAC secret.
	hs256 := func(secret []byte) string {
		input := b64([]byte(toJSON(obj{"alg": "HS256", "kid": rs.kid, "typ": "JWT"}))) + "." + b64([]byte(claimsJSON))
		mac := hmac.New(sha256.New, secret)
		mac.Write([]byte(input))
		return input + "." + b64(mac.Sum(nil))
	}
	spki, err := x509.MarshalPKIXPublicKey(&rs.rsa.PublicKey)
	must(err)
	publicPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: spki})

	const evilJWKS = "https://attacker.example/.well-known/jwks.json"
	const evilCert = "https://attacker.example/cert.pem"

	ok := func(name, about, token string) Case { return Case{name, about, token, "ok"} }
	bad := func(name, expect, about, token string) Case { return Case{name, about, token, expect} }

	return []Case{
		// ----- Accepted -----------------------------------------------------
		ok("valid-rs256", "A well-formed RS256 token from the issuer.", valid),
		ok("valid-es256", "A well-formed ES256 token from the issuer.", validES),
		ok("valid-aud-array", "aud is an array that contains the expected audience.",
			rs.token(obj{"aud": []any{"https://other.example", audience}})),
		ok("valid-aud-array-mixed-types", "Non-string aud entries are ignored, not fatal.",
			rs.token(obj{"aud": []any{7, nil, audience}})),
		ok("valid-no-iat-no-nbf", "iat and nbf are optional.", rs.token(obj{"iat": nil})),
		ok("valid-fractional-exp", "NumericDate may have a fractional part.",
			rs.signed(rsHeader, fmt.Sprintf(`{"iss":%q,"aud":%q,"exp":%d.5}`, issuer, audience, now+3600))),
		ok("valid-exp-within-skew", "Expired 59 s ago, inside the 60 s clock skew.", rs.token(obj{"exp": now - 59})),
		ok("valid-nbf-within-skew", "Not valid for another 60 s, inside the clock skew.", rs.token(obj{"nbf": now + 60})),
		ok("valid-iat-within-skew", "Issued 60 s in the future, inside the clock skew.", rs.token(obj{"iat": now + 60})),
		ok("valid-huge-exp", "exp far beyond any calendar (1e300) is still a finite number.", rs.token(obj{"exp": 1e300})),
		ok("valid-jku-x5u-ignored", "A genuine token whose header also carries jku and x5u. They must be ignored, not followed.",
			rs.tokenWithHeader(obj{"jku": evilJWKS, "x5u": evilCert})),
		ok("valid-unknown-header-members", "Header members jwkit does not know are ignored.",
			rs.tokenWithHeader(obj{"x-custom": obj{"a": 1}, "cty": "example"})),
		ok("valid-no-typ", "typ is optional.", rs.tokenWithHeader(obj{"typ": nil})),
		ok("valid-duplicate-alg-last-wins", "Duplicate header member: both JSON parsers keep the last one, RS256.",
			rs.signed(`{"alg":"none","alg":"RS256","kid":"`+rs.kid+`"}`, claimsJSON)),
		ok("valid-whitespace-around-json", "JSON whitespace before and after the header and payload objects.",
			rs.signed(" "+rsHeader+"\n", "\t"+claimsJSON+" ")),
		ok("valid-prototype-named-claims", "Claims named __proto__ and constructor are ordinary claims.",
			rs.signed(rsHeader, fmt.Sprintf(`{"__proto__":{"iss":"x"},"constructor":"x","iss":%q,"aud":%q,"exp":%d}`, issuer, audience, now+3600))),
		ok("valid-at-size-limit", fmt.Sprintf("A valid token of exactly %d bytes, the size limit.", maxTokenBytes), rs.paddedTo(maxTokenBytes)),

		// ----- Time ---------------------------------------------------------
		bad("expired", "ErrExpired", "exp is an hour in the past.", rs.token(obj{"exp": now - 3600})),
		bad("expired-es256", "ErrExpired", "The same, for an ES256 token.", es.token(obj{"exp": now - 3600})),
		bad("expired-at-skew-boundary", "ErrExpired", "exp + skew equals now exactly: no longer valid.", rs.token(obj{"exp": now - 60})),
		bad("exp-underflows-to-zero", "ErrExpired", "exp is 1e-400, which every double parser reads as 0.",
			rs.signed(rsHeader, fmt.Sprintf(`{"iss":%q,"aud":%q,"exp":1e-400}`, issuer, audience))),
		bad("not-yet-valid", "ErrNotYetValid", "nbf is 61 s in the future, just outside the clock skew.", rs.token(obj{"nbf": now + 61})),
		bad("issued-in-the-future", "ErrNotYetValid", "iat is an hour in the future.", rs.token(obj{"iat": now + 3600})),
		bad("missing-exp", "ErrMalformed", "A token without exp never expires; jwkit requires exp.", rs.token(obj{"exp": nil})),
		bad("exp-is-a-string", "ErrMalformed", "exp must be a JSON number.", rs.token(obj{"exp": fmt.Sprint(now + 3600)})),
		bad("exp-overflows-double", "ErrMalformed", "exp is 1e400: Infinity in JavaScript, a range error in Go. Both must reject it.",
			rs.signed(rsHeader, fmt.Sprintf(`{"iss":%q,"aud":%q,"exp":1e400}`, issuer, audience))),
		bad("nbf-is-a-string", "ErrMalformed", "nbf must be a JSON number when present.", rs.token(obj{"nbf": "soon"})),
		bad("iat-is-null", "ErrMalformed", "A present-but-null iat is not a number.",
			rs.signed(rsHeader, fmt.Sprintf(`{"iss":%q,"aud":%q,"exp":%d,"iat":null}`, issuer, audience, now+3600))),

		// ----- Issuer and audience -------------------------------------------
		bad("wrong-issuer", "ErrBadIssuer", "Signed by the right key but iss names someone else.", rs.token(obj{"iss": "https://evil.example"})),
		bad("missing-issuer", "ErrBadIssuer", "No iss claim.", rs.token(obj{"iss": nil})),
		bad("issuer-is-an-array", "ErrBadIssuer", "iss must be a string.", rs.token(obj{"iss": []any{issuer}})),
		bad("issuer-trailing-slash", "ErrBadIssuer", "Issuer comparison is exact; no URL normalisation.", rs.token(obj{"iss": issuer + "/"})),
		bad("wrong-audience", "ErrBadAudience", "aud names a different API.", rs.token(obj{"aud": "https://other.example"})),
		bad("missing-audience", "ErrBadAudience", "No aud claim.", rs.token(obj{"aud": nil})),
		bad("audience-array-without-ours", "ErrBadAudience", "aud is an array that lacks the expected audience.", rs.token(obj{"aud": []any{"a", "b"}})),
		bad("audience-is-a-number", "ErrBadAudience", "aud must be a string or an array.", rs.token(obj{"aud": 42})),
		bad("wrong-issuer-and-expired", "ErrBadIssuer", "Two faults: the issuer check comes first.", rs.token(obj{"iss": "https://evil.example", "exp": now - 3600})),
		bad("wrong-audience-and-expired", "ErrBadAudience", "Two faults: the audience check comes before expiry.", rs.token(obj{"aud": "https://other.example", "exp": now - 3600})),
		bad("claims-inside-proto-member", "ErrBadIssuer", "The real claims sit under a member named __proto__. JavaScript code that copies the payload with assignment semantics (Object.assign) would turn that member into the object's prototype and then find the claims on it.",
			rs.signed(rsHeader, fmt.Sprintf(`{"__proto__":{"iss":%q,"aud":%q,"exp":%d}}`, issuer, audience, now+3600))),

		// ----- Signature ----------------------------------------------------
		bad("tampered-payload", "ErrBadSignature", "sub changed to admin after signing.", vh+"."+adminPayload+"."+vs),
		bad("tampered-signature", "ErrBadSignature", "One bit of the signature flipped.", vh+"."+vp+"."+flip(vs)),
		bad("tampered-header", "ErrBadSignature", "One header member changed after signing.",
			b64([]byte(toJSON(rs.header(obj{"typ": "at+jwt"}))))+"."+vp+"."+vs),
		bad("wrong-key-same-kid", "ErrBadSignature", "Signed by the attacker's key but labelled with the issuer's kid.", attacker.as(rs.kid).token()),
		bad("signature-from-another-token", "ErrBadSignature", "A genuine signature transplanted onto different claims.",
			vh+"."+b64([]byte(toJSON(claims(obj{"exp": now + 999999}))))+"."+vs),
		bad("empty-signature", "ErrBadSignature", "An RS256 header with the signature removed.", vh+"."+vp+"."),
		bad("expired-and-tampered", "ErrBadSignature", "Two faults: the signature is checked before any claim.",
			vh+"."+b64([]byte(toJSON(claims(obj{"exp": now - 3600}))))+"."+vs),
		bad("es256-header-rsa-kid", "ErrBadSignature", "An ES256 token whose kid names the RSA key. A key is only ever used with its own algorithm.", es.as(rs.kid).token()),
		bad("rs256-header-ec-kid", "ErrBadSignature", "An RS256 token whose kid names the EC key.", rs.as(es.kid).token()),
		bad("es256-tampered-payload", "ErrBadSignature", "ES256: sub changed to admin after signing.", eh+"."+adminPayload+"."+esig),
		bad("es256-tampered-signature", "ErrBadSignature", "ES256: one bit of the signature flipped.", eh+"."+ep+"."+flip(esig)),
		bad("es256-der-signature", "ErrBadSignature", "A correct ECDSA signature in ASN.1 DER instead of the 64-byte r||s form JWS requires.",
			eh+"."+ep+"."+b64(es.signDER(eh+"."+ep))),
		bad("es256-signature-extra-byte", "ErrBadSignature", "A correct r||s signature with a zero byte prepended (65 bytes).",
			eh+"."+ep+"."+b64(append([]byte{0}, es.sign(eh+"."+ep)...))),
		bad("embedded-jwk-attacker-key", "ErrBadSignature", "Signed by the attacker, who helpfully embeds their own public key in the jwk header.",
			attacker.as(rs.kid).tokenWithHeader(obj{"jwk": attacker.publicJWK()})),
		bad("jku-injection-issuer-kid", "ErrBadSignature", "Signed by the attacker, issuer's kid, jku pointing at the attacker's JWKS.",
			attacker.as(rs.kid).tokenWithHeader(obj{"jku": evilJWKS})),
		bad("x5u-injection-issuer-kid", "ErrBadSignature", "Signed by the attacker, issuer's kid, x5u pointing at the attacker's certificate.",
			attacker.as(rs.kid).tokenWithHeader(obj{"x5u": evilCert})),

		// ----- Key lookup ---------------------------------------------------
		bad("unknown-kid", "ErrUnknownKey", "Signed by a key the issuer never published.", attacker.token()),
		bad("jku-injection-attacker-kid", "ErrUnknownKey", "Signed by the attacker under their own kid, with jku pointing at a JWKS that contains it.",
			attacker.tokenWithHeader(obj{"jku": evilJWKS})),
		bad("weak-rsa-key", "ErrUnknownKey", "Correctly signed by a published 1024-bit RSA key. Keys under 2048 bits are never loaded.", keys.rsaWeak.token()),
		bad("p384-key-for-es256", "ErrUnknownKey", "Signed (ECDSA, SHA-256) by a published P-384 key. Only P-256 keys are loaded for ES256.", keys.ecP384.token()),
		bad("encryption-key", "ErrUnknownKey", "Correctly signed by a published key marked use=enc. Encryption keys are never loaded.", keys.rsaEnc.token()),
		bad("key-pinned-to-ps256", "ErrUnknownKey", "Correctly signed (RS256) by a published key whose JWK says alg=PS256. The key's own alg is respected.", keys.rsaPS256.token()),

		// ----- Algorithms ---------------------------------------------------
		bad("alg-none", "ErrUnsupportedAlg", `The classic: {"alg":"none"} and an empty signature.`, unsigned(obj{"alg": "none", "typ": "JWT"})),
		bad("alg-none-with-kid", "ErrUnsupportedAlg", "alg none, naming the issuer's key.", unsigned(obj{"alg": "none", "kid": rs.kid})),
		bad("alg-none-mixed-case", "ErrUnsupportedAlg", `"nOnE": case tricks do not help.`, unsigned(obj{"alg": "nOnE", "kid": rs.kid})),
		bad("alg-none-with-signature", "ErrUnsupportedAlg", "alg none, but carrying a genuine RS256 signature for the original header.",
			b64([]byte(toJSON(obj{"alg": "none", "kid": rs.kid})))+"."+vp+"."+vs),
		bad("hs256-rsa-public-key-pem", "ErrUnsupportedAlg", "Algorithm confusion: HS256 keyed with the issuer's RSA public key in PEM form.", hs256(publicPEM)),
		bad("hs256-rsa-public-key-der", "ErrUnsupportedAlg", "Algorithm confusion: HS256 keyed with the issuer's RSA public key in DER form.", hs256(spki)),
		bad("alg-hs384", "ErrUnsupportedAlg", "No HMAC algorithm is accepted.", rs.tokenWithHeader(obj{"alg": "HS384"})),
		bad("alg-rs384", "ErrUnsupportedAlg", "RS384 is not on the allow-list.", rs.tokenWithHeader(obj{"alg": "RS384"})),
		bad("alg-ps256", "ErrUnsupportedAlg", "PS256 is not on the allow-list.", rs.tokenWithHeader(obj{"alg": "PS256"})),
		bad("alg-es384", "ErrUnsupportedAlg", "ES384 is not on the allow-list.", es.tokenWithHeader(obj{"alg": "ES384"})),
		bad("alg-lower-case", "ErrUnsupportedAlg", `"rs256": algorithm names are case-sensitive.`, rs.tokenWithHeader(obj{"alg": "rs256"})),
		bad("alg-empty", "ErrUnsupportedAlg", "alg is the empty string.", rs.tokenWithHeader(obj{"alg": ""})),
		bad("alg-missing", "ErrMalformed", "No alg member at all.", rs.tokenWithHeader(obj{"alg": nil})),
		bad("alg-is-a-number", "ErrMalformed", "alg must be a string.", rs.tokenWithHeader(obj{"alg": 256})),
		bad("alg-member-upper-case", "ErrMalformed", `The member is spelled "ALG". Member names are case-sensitive, so there is no alg.`,
			rs.signed(`{"ALG":"RS256","kid":"`+rs.kid+`"}`, claimsJSON)),
		bad("alg-inside-proto-member", "ErrMalformed", "alg and kid sit under a member named __proto__, where only code that lets it become the object's prototype would find them.",
			rs.signed(`{"__proto__":{"alg":"RS256","kid":"`+rs.kid+`"}}`, claimsJSON)),

		// ----- Header policy ------------------------------------------------
		bad("missing-kid", "ErrMalformed", "No kid: jwkit never guesses which key to try.", rs.tokenWithHeader(obj{"kid": nil})),
		bad("empty-kid", "ErrMalformed", "kid is the empty string.", rs.tokenWithHeader(obj{"kid": ""})),
		bad("kid-is-a-number", "ErrMalformed", "kid must be a string.", rs.tokenWithHeader(obj{"kid": 1})),
		bad("crit-header", "ErrMalformed", "A crit header demands extensions jwkit does not implement (RFC 7515, 4.1.11).", rs.tokenWithHeader(obj{"crit": []any{"exp"}})),

		// ----- Structure ----------------------------------------------------
		bad("empty-token", "ErrMalformed", "The empty string.", ""),
		bad("one-segment", "ErrMalformed", "No dots at all.", "abc"),
		bad("two-segments", "ErrMalformed", "Header and payload, no signature segment.", vh+"."+vp),
		bad("four-segments", "ErrMalformed", "One segment too many.", valid+".abc"),
		bad("five-segments", "ErrMalformed", "Five segments: the shape of a JWE.", valid+".abc.def"),
		bad("only-dots", "ErrMalformed", "Three empty segments.", ".."),
		bad("bearer-prefix", "ErrMalformed", `The Authorization header value, "Bearer " included, passed as the token.`, "Bearer "+valid),
		bad("leading-space", "ErrMalformed", "A space before the token.", " "+valid),
		bad("trailing-newline", "ErrMalformed", "A newline after the token.", valid+"\n"),
		bad("newline-inside-header", "ErrMalformed", "A line break inside a segment. Go's base64 decoder would skip it silently.", vh[:10]+"\n"+vh[10:]+"."+vp+"."+vs),
		bad("invalid-base64url-header", "ErrMalformed", "A character outside the base64url alphabet in the header.", "!"+vh[1:]+"."+vp+"."+vs),
		bad("invalid-base64url-payload", "ErrMalformed", "A character outside the base64url alphabet in the payload.", vh+"."+vp[:5]+"*"+vp[6:]+"."+vs),
		bad("invalid-base64url-signature", "ErrMalformed", "A character outside the base64url alphabet in the signature. Node's decoder would skip it silently.", vh+"."+vp+"."+vs[:5]+"~"+vs[6:]),
		bad("standard-base64-alphabet", "ErrMalformed", "The signature uses '+', from the standard rather than URL-safe alphabet.", vh+"."+vp+".+"+vs[1:]),
		bad("padded-base64", "ErrMalformed", "The signature carries '=' padding.", vh+"."+vp+"."+vs+"=="),
		bad("impossible-base64-length", "ErrMalformed", "A signature segment whose length is 1 mod 4, which no byte string encodes to.", vh+"."+vp+"."+vs+"AAA"),
		bad("non-canonical-base64-signature", "ErrMalformed", "Only the unused trailing bits of the signature's last character differ. A lenient decoder would accept this as the same, valid, signature.", vh+"."+vp+"."+nonCanonical(vs)),
		bad("non-ascii-character", "ErrMalformed", "A non-ASCII letter in the payload segment.", vh+"."+vp+"é."+vs),
		bad("header-not-json", "ErrMalformed", "The header decodes to text that is not JSON.", rs.signed("not json", claimsJSON)),
		bad("header-json-array", "ErrMalformed", "The header is a JSON array.", rs.signed(`["RS256"]`, claimsJSON)),
		bad("header-json-null", "ErrMalformed", "The header is JSON null.", rs.signed("null", claimsJSON)),
		bad("empty-header", "ErrMalformed", "The header segment is empty.", "."+vp+"."+vs),
		bad("payload-not-json", "ErrMalformed", "The payload is truncated JSON.", rs.signed(rsHeader, `{"iss":`)),
		bad("payload-json-string", "ErrMalformed", "The payload is a JSON string, not an object.", rs.signed(rsHeader, `"claims"`)),
		bad("nested-jwt", "ErrMalformed", `A correctly signed JWT whose payload is another JWT (cty "JWT"). jwkit does not unwrap nested tokens.`,
			rs.signed(toJSON(obj{"alg": "RS256", "kid": rs.kid, "cty": "JWT"}), valid)),
		bad("payload-trailing-data", "ErrMalformed", "A second JSON value after the claims object.", rs.signed(rsHeader, claimsJSON+"{}")),
		bad("payload-stray-brace", "ErrMalformed", "An extra closing brace after the claims object.", rs.signed(rsHeader, claimsJSON+"}")),
		bad("payload-invalid-utf8", "ErrMalformed", "The payload contains the byte 0xFF, which is not valid UTF-8. Correctly signed.", rs.signed(rsHeader, "{\"iss\":\"\xff\"}")),
		bad("payload-byte-order-mark", "ErrMalformed", "The payload starts with a UTF-8 byte order mark. Correctly signed. JavaScript's TextDecoder would strip it silently.", rs.signed(rsHeader, "\xef\xbb\xbf"+claimsJSON)),

		// ----- Size ---------------------------------------------------------
		bad("one-byte-over-size-limit", "ErrMalformed", fmt.Sprintf("A correctly signed token of %d bytes, one over the limit.", maxTokenBytes+1), rs.paddedTo(maxTokenBytes+1)),
		bad("extremely-long-token", "ErrMalformed", "A correctly signed token of roughly 64 KiB.", rs.token(obj{"pad": strings.Repeat("x", 48000)})),
	}
}
